<footer>

	<article class="main-footer">
        <div class="footer-logo">
            <img src="../assets/revolution-fc-logo-white.svg" alt="logo Revolution FC" />
        </div>
        <ul class="footer-nav">
            <li class="list-header">Le Club</li>
            <li><a href="https://www.eletto-revolution.com">Boutique du club</a></li>
            <li><a href="../club/membres_ca">Membres du C.A.</a></li>
            <li><a href="../club/membres_admin">Membres administratif</a></li>
            <li><a href="../club/assurances">Assurances</a></li>
            <li><a href="../club/aide-financiere">Aides financi&egrave;res</a></li>
            <li><a href="../contact">Contact</a></li>
        </ul>
        <ul class="footer-nav">
            <li class="list-header">Technique</li>
            <li><a href="../staff_technique">Staff technique</a></li>
            <li><a href="../programmes">Nos programmes</a></li>
            <!--<li><a href="../entraineurs">Ressources entraineurs</a></li>-->
        </ul>
        <ul class="footer-nav">
            <li class="list-header">Politiques</li>
            <li><a href="../docs/Guide-pour-la-se-Acurite-A-Soccer-CANADA.pdf" target="_blank">Guide pour la s&eacute;curit&eacute; - SC</a></li>
            <li><a href="../docs/Regle-de-2-Soccer-Canada.pdf" target="_blank">Règle de deux - SC</a></li>
            <li><a href="../docs/Code-de-conduite-RFC-1.pdf" target="_blank">Code de conduite pour protéger les enfants</a></li>
            <li><a href="../docs/Interaction-adulte-enfant-RFC-1.pdf" target="_blank">Intéraction Adulte - Enfant</a></li>
            <li><a href="../docs/Politique-de-remboursement.pdf" target="_blank">Remboursement</a></li>
            <li><a href="../docs/Politique-de-remboursement.pdf" target="_blank">Protocole de plainte</a></li>
            <li><a href="../docs/Protocole-de-gestion-des-commotions-cerebrales.pdf" target="_blank">Protocole de gestion des commotions cérébrales</a></li>
        </ul>
        <ul class="footer-nav">
            <li class="list-header">Codes de conduite</li>
            <li><a href="../docs/CodeEthique.pdf" target="_blank">Code éthique du joueur</a></li>
            <!--<li><a href="../politiques/Code-de-conduite.pdf" target="_blank">Ligne directrice du club</a></li>
            <li><a href="../politiques/code-conduite-entraineurs.pdf" target="_blank">Entraineur</a></li>
            <li><a href="../politiques/code-conduite-parents.pdf" target="_blank">Parents</a></li>
            <li><a href="../politiques/code-conduite-joueur.pdf" target="_blank">Joueur / Joueuse</a></li>-->
        </ul>
		<div class="footer-copy">
			<p>&copy; <?php echo date("Y"); ?> R&eacute;volution FC - Tous droits réservés - Aucune reproduction partielle ou total du site et de son contenu n'est autorisé </p>
			<p>Site concu et r&eacute;alis&eacute; par <a href="https://www.chabertdesign.com" target="_blank" rel="noreferrer">Chabert Design</a></p>
		</div>
	</article>

</footer>


</body>
</html>