</main>

<footer>

	<article class="main-footer">
        <div class="footer-logo">
            <img src="../assets/revolution-fc-logo-white.svg" alt="logo Revolution FC" />
        </div>
        <ul class="footer-nav">
            <li class="list-header">Le Club</li>
            <li><a href="<?php echo $storeUrl ?>">Boutique du club</a></li>
            <li><a href="/club/membres_ca">Membres du C.A.</a></li>
            <li><a href="/club/membres_admin">Membres administratif</a></li>
            <li><a href="/contact">Contact</a></li>
        </ul>
        <ul class="footer-nav">
            <li class="list-header">Technique</li>
            <li><a href="/staff_technique">Staff technique</a></li>
            <li><a href="/programmes">Nos programmes</a></li>
            <!--<li><a href="../entraineurs">Ressources entraineurs</a></li>-->
        </ul>
        <ul class="footer-nav">
            <li class="list-header">Documents</li>
            <li><a href="/documents?category=1">La sécurité des enfants</a></li>
            <li><a href="/documents?category=2">Documents de références</a></li>
            <li><a href="/club/aide-financiere">Aides financi&egrave;res</a></li>
        </ul>
        <ul class="footer-nav">
            <li class="list-header">Codes &amp; politiques</li>
            <li><a href="/docs/reglements-generaux.pdf" target="_blank">Règlements généraux</a></li>
            <li><a href="/docs/CodeEthique.pdf" target="_blank">Code éthique du joueur</a></li>
            <li><a href="/politique-confidentialite">Politique de confidentialité</a></li>
            <li><a href="../docs/Politique-de-remboursement.pdf" target="_blank">Remboursement</a></li>
        </ul>
		<div class="footer-copy">
			<p>&copy; <?php echo date("Y"); ?> R&eacute;volution FC - Tous droits réservés - Aucune reproduction partielle ou totale du site et de son contenu n'est autorisée.</p>
			<p>Site concu et r&eacute;alis&eacute; par <a class="inline-link" href="https://www.chabertdesign.com" target="_blank" rel="noreferrer">Chabert Design</a></p>
		</div>
	</article>

</footer>


</body>
</html>