
<li class="menu-element icon i-config">Configuration</li>
<li class="ss-menu-element"><a href="?p=2">Config ADMIN – Jonathan</a></li>
<li class="ss-menu-element"><a href="?p=3">Config générale</a></li>
<li class="ss-menu-element"><a href="?p=4">Page d'accueil</a></li>

<li class="menu-element icon i-news">Actualités</li>
<li class="ss-menu-element"><a href="index.php?p=11">Gérer les actualités</a></li>

<li class="menu-element icon i-rfc-logo">Club</li>
<li class="ss-menu-element"><a href="?p=5">Informations générales</a></li>
<li class="ss-menu-element"><a href="?p=31">Gérer les documents</a></li>
<li class="ss-menu-element"><a href="?p=33">Gérer les catégories de documents</a></li>
<li class="ss-menu-element"><a href="?p=301">Gérer les offres d'emplois</a></li>
<li class="ss-menu-element"><a href="?p=61">Gérer les Terrains</a></li>

<li class="menu-element icon i-user">Personnes</li>
<li class="ss-menu-element"><a href="?p=21">Membres du CA</a></li>
<li class="ss-menu-element"><a href="?p=23">Membres de l'administration</a></li>
<li class="ss-menu-element"><a href="?p=25">Membres du staff technique</a></li>
<li class="ss-menu-element"><a href="?p=93">Gérer les Utlisateurs</a></li>

<li class="menu-element icon i-soccer-1">Technique</li>
<li class="ss-menu-element"><a href="?p=51">Gérer les Programmes</a></li>
<li class="ss-menu-element not-active"><a href="?p=36">Gérer les Documents technique</a></li>
<li class="ss-menu-element not-active"><a href="?p=37">Gérer les catégories technique</a></li>
<li class="ss-menu-element not-active"><a href="?p=38">Gérer les sous-catégories technique</a></li>

<li class="menu-element icon i-tournament">Tournois</li>
<li class="ss-menu-element"><a href="?p=81">Gérer les tournois</a></li>

<li class="menu-element icon i-sponsors"><a href="?p=91">Sponsors</a></li>
<li class="ss-menu-element"><a href="?p=91">Gérer les sponsors</a></li>