<!--For testing purpose-->
<?php if (isset($_SESSION['auth']) && $_SESSION['type'] == 6): ?>
    <li class="menu-element icon i-events">Evenements</li>
    <ul class="sub-nav">
        <li class="sub-nav-item"><a class="sub-nav-item-el" href="?p=63">Voir les events</a></li>
    </ul>
<?php endif ?>


<li class="menu-element icon i-config">Configuration</li>
<ul class="sub-nav">
    <li class="sub-nav-item"><a class="sub-nav-item-el" href="?p=2">Config ADMIN – Jonathan</a></li>
    <li class="sub-nav-item"><a class="sub-nav-item-el" href="?p=3">Config générale</a></li>
    <li class="sub-nav-item"><a class="sub-nav-item-el" href="?p=4">Page d'accueil</a></li>
</ul>

<li class="menu-element icon i-news">Actualités</li>
<ul class="sub-nav">
    <li class="sub-nav-item"><a class="sub-nav-item-el" href="index.php?p=11">Gérer les actualités</a></li>
</ul>

<li class="menu-element icon i-rfc-logo">Club</li>
<ul class="sub-nav">
    <li class="sub-nav-item"><a class="sub-nav-item-el" href="?p=5">Informations générales</a></li>
    <li class="sub-nav-item"><a class="sub-nav-item-el" href="?p=31">Gérer les documents</a></li>
    <li class="sub-nav-item"><a class="sub-nav-item-el" href="?p=33">Gérer les catégories de documents</a></li>
    <li class="sub-nav-item"><a class="sub-nav-item-el" href="?p=301">Gérer les offres d'emplois</a></li>
    <li class="sub-nav-item"><a class="sub-nav-item-el" href="?p=61">Gérer les Terrains</a></li>
</ul>

<li class="menu-element icon i-user">Personnes</li>
<ul class="sub-nav">
    <li class="sub-nav-item"><a class="sub-nav-item-el" href="?p=21">Membres du CA</a></li>
    <li class="sub-nav-item"><a class="sub-nav-item-el" href="?p=23">Membres de l'administration</a></li>
    <li class="sub-nav-item"><a class="sub-nav-item-el" href="?p=25">Membres du staff technique</a></li>
    <li class="sub-nav-item"><a class="sub-nav-item-el" href="?p=93">Gérer les Utlisateurs</a></li>
</ul>

<li class="menu-element icon i-soccer-1">Technique</li>
<ul class="sub-nav">
    <li class="sub-nav-item"><a class="sub-nav-item-el" href="?p=51">Gérer les Programmes</a></li>
    <li class="sub-nav-item"><a class="sub-nav-item-el" href="?p=35">Gérer les Documents technique</a></li>
    <li class="sub-nav-item"><a class="sub-nav-item-el" href="?p=37">Gérer les catégories technique</a></li>
    <li class="sub-nav-item"><a class="sub-nav-item-el" href="?p=38">Gérer les sous-catégories technique</a></li>
</ul>

<li class="menu-element icon i-tournament">Tournois</li>
<ul class="sub-nav">
    <<li class="sub-nav-item"><a class="sub-nav-item-el" href="?p=81">Gérer les tournois</a></li>
</ul>

<li class="menu-element icon i-sponsors">Sponsors</li>
<ul class="sub-nav">
    <li class="sub-nav-item"><a class="sub-nav-item-el" href="?p=91">Gérer les sponsors</a></li>
</ul>